services:
  api:
    build: ./
    image: command-system-api
    # command: sh -c 'npm install && npm run start:dev'
    environment:
      DB_HOST: db-mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db-mysql
    links:
      - db-mysql
    ports:
      - 3001:5000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true

  db-mysql:
    container_name: mysql8
    image: mysql:8.0
    volumes:
      - mysql-command-system-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: command_system
    ports:
      - 3002:3306
    networks:
      - rede-local

volumes:
  mysql-command-system-data:
